language: go
go:
  - 1.13
script:
  - make
before_deploy:
  - make VERSION=${TRAVIS_TAG} release
deploy:
  provider: releases
  api_key:
    secure:
  file: release/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
